stages:
  - release

release_chart:
  stage: release
  image: alpine/helm:3
  script:
    - apk add curl
    - helm lint .
    - helm package .
    - curl -u ${NEXUS_HELM_REPO_USERNAME}:${NEXUS_HELM_REPO_PASSWORD} ${NEXUS_HELM_REPO} --upload-file ./*.tgz

