global:
  imageCredentials:
    registry: 
    username: 
    password: 
    port: 
  backend:
    image: gitlab.praktikum-services.ru:5050/std-ext-011-46/momo-store/backend
    version: '1.0.1897131'
    replicas: 1
    containerPort: "8081"
    internal_svc_name: "backend"
    docker_secret_name: "secret-name"
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-ext-011-46/momo-store/frontend
    version: '1.0.1897130'
    replicas: 1
    containerPort: 8080
    fqdn: "std-ext-011-46.k8s.praktikum-services.tech"
    docker_secret_name: "secret-name"
    vue_app_api_url: "/api" #must be http://<fqdn>:<frontend.containerPort>/api
    node_env: "production"
    permanent_redirect:
      enabled: true 
  prometheus:
    service_name: "momo-store-prometheus"
    basic_auth_login: "user"
    basic_auth_password: "12345"
  grafana:
    service_name: "momo-store-grafana"
    datasorce_uid: "PBFA97CFB590B2093" # don't change this uid
    dashboard_provider_name: "default-provider"
    default_folder_name: "momo-store"
    default_folder_uid: "DDFA66CFB551B2A31"
    basic_auth_login: "user"
    basic_auth_password: "12345"