global:
  imageCredentials:
    registry: gitlab.praktikum-services.ru
    username: std-ext-011-46
    password: djB67L1h
    port: 5050
  backend:
    image: gitlab.praktikum-services.ru:5050/std-ext-011-46/momo-store/backend
    replicas: 2
    containerPort: "8081"
    internal_svc_name: "backend"
    docker_secret_name: "secret-name"
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-ext-011-46/momo-store/frontend
    replicas: 1
    containerPort: 8080
    fqdn: "std-ext-011-46.k8s.praktikum-services.tech"
    docker_secret_name: "secret-name"
    vue_app_api_url: "https://std-ext-011-46.k8s.praktikum-services.tech:8080/api" #must be http://<fqdn>:<frontend.containerPort>/api
    node_env: "production"