---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "6"
    "helm.sh/hook-delete-policy": before-hook-creation
# базовые параметры конфигурации: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
# дополнительный источник: https://github.com/grafana/helm-charts/tree/main/charts/grafana
# подключение дашбордов: https://github.com/grafana/helm-charts/blob/d121761fcae0da38d3e880254ddc24da3088e78b/charts/grafana/values.yaml#L812
# прокси датасорсов с basic_auth: https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
# настройки провиженинга графаны: https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = {{ .Values.global.frontend.fqdn }}
    root_url = /grafana
    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/default.json
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      uid: {{ quote .Values.global.grafana.datasorce_uid }}
      basicAuth: true
      basicAuthUser: {{ .Values.global.prometheus.basic_auth_login }}
      isDefault: true
      name: Prometheus
      secureJsonData:
        basicAuthPassword: {{ .Values.global.prometheus.basic_auth_password }}
      type: prometheus
      url: https://{{ .Values.global.frontend.fqdn }}/prometheus
    deleteDatasources:
    - name: Prometheus
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - name: '{{ .Values.global.grafana.dashboard_provider_name }}'
      orgId: 1
      folder: '{{ .Values.global.grafana.default_folder_name }}'
      folderUid: '{{ .Values.global.grafana.default_folder_uid }}'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 30
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards
        # <bool> use folder names from filesystem to create folders in Grafana
        foldersFromFilesStructure: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "6"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  default.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 7,
      "links": [],
      "panels": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "{{ .Values.global.grafana.datasource_uid }}"
          },
          "gridPos": {
            "h": 3,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "{{ .Values.global.grafana.datasource_uid }}"
              },
              "refId": "A"
            }
          ],
          "type": "welcome"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "{{ .Values.global.grafana.datasource_uid }}"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 7,
            "w": 24,
            "x": 0,
            "y": 3
          },
          "id": 5,
          "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
              "calcs": [
                "lastNotNull"
              ],
              "fields": "",
              "values": false
            },
            "showPercentChange": false,
            "textMode": "auto",
            "wideLayout": true
          },
          "pluginVersion": "11.0.0",
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "{{ .Values.global.grafana.datasource_uid }}"
              },
              "disableTextWrap": false,
              "editorMode": "builder",
              "expr": "up",
              "fullMetaSearch": false,
              "includeNullMetadata": true,
              "instant": false,
              "legendFormat": "__auto",
              "range": true,
              "refId": "A",
              "useBackend": false
            }
          ],
          "title": "Total Backend Instances ",
          "type": "stat"
        },
        {
          "collapsed": false,
          "gridPos": {
            "h": 1,
            "w": 24,
            "x": 0,
            "y": 10
          },
          "id": 4,
          "panels": [],
          "title": "Business metrics ",
          "type": "row"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "{{ .Values.global.grafana.datasource_uid }}"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 11
          },
          "id": 2,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "maxHeight": 600,
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "{{ .Values.global.grafana.datasource_uid }}"
              },
              "disableTextWrap": false,
              "editorMode": "builder",
              "expr": "rate(requests_count[10m])",
              "fullMetaSearch": false,
              "includeNullMetadata": true,
              "instant": false,
              "legendFormat": "__auto",
              "range": true,
              "refId": "A",
              "useBackend": false
            }
          ],
          "title": "Rate requests",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "{{ .Values.global.grafana.datasource_uid }}"
          },
          "description": "Most popular dumpling listing score",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 11
          },
          "id": 3,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "maxHeight": 600,
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "{{ .Values.global.grafana.datasource_uid }}"
              },
              "disableTextWrap": false,
              "editorMode": "builder",
              "expr": "avg by(id) (dumplings_listing_count)",
              "fullMetaSearch": false,
              "includeNullMetadata": true,
              "instant": false,
              "legendFormat": "__auto",
              "range": true,
              "refId": "A",
              "useBackend": false
            }
          ],
          "title": "Dumpling listing scores",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "{{ .Values.global.grafana.datasource_uid }}"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "fillOpacity": 80,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineWidth": 1,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 19
          },
          "id": 6,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "{{ .Values.global.grafana.datasource_uid }}"
              },
              "disableTextWrap": false,
              "editorMode": "builder",
              "expr": "histogram_quantile(0.95, sum by(le) (rate(response_timing_ms_bucket[10m])))",
              "fullMetaSearch": false,
              "includeNullMetadata": false,
              "instant": false,
              "legendFormat": "__auto",
              "range": true,
              "refId": "A",
              "useBackend": false
            }
          ],
          "title": "Histogram Quontile",
          "type": "histogram"
        }
      ],
      "refresh": "",
      "schemaVersion": 39,
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-15m",
        "to": "now"
      },
      "timeRangeUpdatedDuringEditOrView": false,
      "timepicker": {},
      "timezone": "Europe/Moscow",
      "title": "Momo-store Dashboard",
      "uid": "eeff6ireychz4a",
      "version": 2,
      "weekStart": ""
    }
  


