---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "6"
    "helm.sh/hook-delete-policy": before-hook-creation
# базовые параметры конфигурации: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
# дополнительный источник https://github.com/grafana/helm-charts/tree/main/charts/grafana
# подключение дашбордов https://github.com/grafana/helm-charts/blob/d121761fcae0da38d3e880254ddc24da3088e78b/charts/grafana/values.yaml#L812
# конфиг датасорса сначала проверить на чарте как он монтируется и на конфиг https://github.com/grafana/helm-charts/blob/d121761fcae0da38d3e880254ddc24da3088e78b/charts/grafana/values.yaml#L657
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = {{ .Values.global.frontend.fqdn }}
    root_url = /grafana


