apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-grafana
  namespace: {{ .Release.Namespace }}
  {{ include "grafana.alb.annotations" . }}
  labels:
    app: prometheus
  annotations:
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#authentication
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret-type: auth-file
    nginx.ingress.kubernetes.io/auth-secret: {{ .Release.Name }}-grafana
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - {{ quote .Values.global.frontend.fqdn }}
      secretName: k8s-secret
  rules:
    - host: {{ quote .Values.global.frontend.fqdn }}
      http:
        paths:
        - path: /grafana(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service: 
              name: {{ .Values.global.grafana.service_name }}
              port:
                number: 3000
