apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "9"
    "helm.sh/hook-delete-policy": before-hook-creation
  # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#authentication
  # https://kubernetes.github.io/ingress-nginx/examples/auth/basic/
type: Opaque
data:
  auth: {{ ( htpasswd .Values.global.grafana.basic_auth_login .Values.global.grafana.basic_auth_password ) | b64enc }}