apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.grafana.service_name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "8"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: ClusterIP