apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
  annotations:
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#authentication
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret-type: auth-map
    nginx.ingress.kubernetes.io/auth-secret: {{ .Release.Name }}-prometheus
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - {{ quote .Values.global.frontend.fqdn }}
  rules:
    - host: {{ quote .Values.global.frontend.fqdn }}
      http:
        paths:
        - path: /prometheus(/|$)(.*)
          pathType: Prefix
          backend:
            service: 
              name: {{ quote .Values.global.prometheus.service_name }}
              port:
                number: 9090
