---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: prometheus-agent-role
    namespace: {{ .Release.Namespace }}
rules:
    - apiGroups:
        - ''
      resources:
        - 'pods'
      verbs:
        - 'get'
        - 'list'
---