apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: prometheus-agent-rolebind
    namespace: {{ .Release.Namespace }}
subjects:
    - kind: ServiceAccount
      name: prometheus-agent
      namespace: {{ .Release.Namespace }}
roleRef:
    kind: Role
    name: prometheus-agent-role
    apiGroup: rbac.authorization.k8s.io