apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-prometheus
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.global.prometheus.basic_auth_login)}}:{{ htpasswd .Values.global.prometheus.basic_auth_login .Values.global.prometheus.basic_auth_password }}