apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{ include "frontend.labels" . }}
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - {{ quote .Values.global.frontend.fqdn  }}
  rules:
    - host: {{ quote .Values.global.frontend.fqdn  }}
      http:
        paths:
        - path: /momo-store
          pathType: Prefix
          backend:
            service:
              name: {{ .Chart.Name }}-{{ .Release.Name }}
              port:
                number: {{ .Values.global.frontend.containerPort }} 
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend-momo-store
              port:
                number: {{ .Values.global.backend.containerPort }} 
        - path: /prometheus
          pathType: Prefix
          backend:
            service: 
              name: {{ quote .Values.global.prometheus.service_name }}
              port:
                number: 9090
        - path: /grafana
          pathType: Prefix
          backend:
            service:
              name: "my-grafana"
              port:
                number: 80