apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{ include "frontend.labels" . }}
  {{ include "frontend.alb.annotations" . }}
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - {{ quote .Values.global.frontend.fqdn  }}
      secretName: yc-certmgr-cert-id-{{ .Values.global.cm.cert_id }}
  rules:
    - host: {{ quote .Values.global.frontend.fqdn  }}
      http:
        paths:
        - path: /momo-store
          pathType: Prefix
          backend:
            service:
              name: {{ .Chart.Name }}-{{ .Release.Name }}
              port:
                number: {{ .Values.global.frontend.containerPort }} 
        {{ if .Values.global.frontend.permanent_redirect.enabled }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Chart.Name }}-{{ .Release.Name }}
              port:
                number: {{ .Values.global.frontend.containerPort | add1 }}
        {{ end }}
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend-momo-store
              port:
                number: {{ .Values.global.backend.containerPort }} 