apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  {{ include "backend.labels" . }}

# было бы хорошим тоном добавить аутентификацию на nginx, а в prometheus указать серт для скраппинга метрик 
data:
  default.conf: | 
    server {
        listen {{ .Values.global.backend.containerPort | atoi | add1 }};

        location /api/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://localhost:{{ .Values.global.backend.containerPort }}/;
        }
    }
