apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{ template "backend.labels" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.backend.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.global.backend.containerPort | atoi | add1 }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
